#____   ___ ___ _   _ _____
# |  _ \ / _ \_ _| \ | |_   _|
# | |_) | | | | ||  \| | | |
# |  __/| |_| | || |\  | | |
# |_|    \___/___|_| \_| |_|
#
货币名称: "点券"

# 点券的基础数量
基础数量: 0.0

# 点券的最大值
点券最大值: 999999999.0

喊话冷却: 10

排行榜显示玩家数量: 10
